name:  Static HTML Deployment to Ubuntu Server

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Build Print Statement
        run: echo "This is a build job"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Test Print Statement
        run: echo "This is a test job"

  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Copy the Index.html to Ubuntu Server
      - uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'index.html'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/index.html'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.HOST}}                                      # Remote server address - REQUIRED true
          user: ${{secrets.USER}}                                      # Remote server user - REQUIRED true
          key: ${{secrets.KEY}}                                        # Remote server private key - REQUIRED at least one of "password" or "key" 
          pre_upload: sudo rm -rf /var/www/html/index.html  # Command to run via ssh before scp upload - REQUIRED false
          post_upload: sudo mv ~/index.html /var/www/html/. # Command to run via ssh after scp upload - REQUIRED false
          ssh_options: -o StrictHostKeyChecking=no                     # A set of ssh_option separated by -o - REQUIRED false - DEFAULT -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
